language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

install:
    - make install

script:
    - make test

notifications:
  email:
    on_success: change
    on_failure: change
